<?php
/**
 * TNW_Stripe extension
 * NOTICE OF LICENSE
 *
 * This source file is subject to the OSL 3.0 License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @category  TNW
 * @package   TNW_Stripe
 * @copyright Copyright (c) 2017-2018
 * @license   Open Software License (OSL 3.0)
 */

/**
 * @var TNW\Stripe\Block\Payment $block
 * @var Magento\Framework\Escaper $escaper
 * @var \TNW\Stripe\ViewModel\StoredCards $viewModel
 */

$viewModel = $block->getViewModel();
$email = $viewModel ? $viewModel->getCustomer()->getEmail() : null;

?>
<script type="text/x-magento-init">
{
    "#stored-cards-info": {
        "TNW_Stripe/js/customer/card/stripe": {
            "customerEmail" : "<?= $escaper->escapeHtml($email) ?>",
            "clientConfig" : <?= /* @noEscape */ $block->getPaymentConfig(); ?>
        }
    }
}
</script>
